{{$installationSharedUuid:=uuidv4}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Release.Namespace }}
  annotations:
    installation-shared-uuid: {{ $installationSharedUuid }}
spec:
  selector:
    matchLabels:
      app: sample-check-license
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-check-license
    spec:
      containers:
        - name: sample-check-license
          command: ["/sample-check-license",
            "-cluster-id", "{{.Values.clusterId}}",
            "-secret-file", "/etc/sample-check-license-secrets/sa-key.json",
            "-license-id", "{{.Values.licenseId}}",
            "-uuid", {{$installationSharedUuid}}]
          image: {{.Values.image.repository}}:{{.Values.image.tag}}
          imagePullPolicy: {{.Values.image.pullPolicy}}
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: sa-key
              mountPath: "/etc/sample-check-license-secrets"
              readOnly: true
      volumes:
        - name: sa-key
          secret:
            secretName: {{ .Values.saKeySecretName }}
            items:
              - key: {{ .Values.saKeySecretKeyFile }}
                path: sa-key.json